# This is a basic workflow to help you get started with Actions

name: Build Artifact

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2.3.2
        with:
          python-version: 3.9
          cache: pip
      - name: Install requirements and PyInstaller
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install setuptools
          pip install -r requirements.txt
          pip install pyinstaller
      - name: Run PyInstaller
        run: |
          pyinstaller --noconfirm --onedir --console --add-data "templates;templates/" --add-data "static;static/"  "huji_cheese.py"
      - name: Zip output
        run: zip -r output output\*
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          path: output.zip
